### ISSUE TITLE
Cluster Add Errors Out

### ISSUE THREAD

**Issue by sjfloat** [getcarina/feedback#10]
My attempt to add a cluster chugs a few moments and ends with 'status error'.

**Comment by sjfloat** [comment]
My failed initial attempt 'Alpha' had autoscaling enabled. My second did not and seems to have succeeded.

**Comment by rgbkrk** [comment]
UI or cli?

**Comment by sjfloat** [comment]
UI, it was my very first thrust into this.

**Comment by simonjj** [comment]
this was investigated to be an unresponsive note, consecutive creates succeeded. closing this issue.
