### ISSUE TITLE
corina assumes bash

### ISSUE THREAD

**Issue by sjfloat** [getcarina/feedback#11]
I use tcsh and zsh is an increasingly popular shell.

**Comment by rgbkrk** [comment]
Which part, the credential sourcing? What would it need to change to for you?

**Comment by rgbkrk** [comment]
Ah, I'm assuming this is for `docker.env`. One thing that docker-machine does is check the `$SHELL` environment variable, spitting out, at the very least, `fish` compatible outputs. Our credentials env can't be dynamic like this I assume. We could handle this in `carina` (or it would be part of a `docker-machine` plugin).

**Comment by sjfloat** [comment]
Looks like one could generalize this:

https://github.com/getcarina/libcarina/blob/master/libcarina.go#L230

**Comment by sjfloat** [comment]
Sorry. I meant hereabouts:

https://github.com/getcarina/libcarina/blob/master/libcarina.go#L249

**Comment by mdarby** [comment]
Unsure where this reference was; or what the actual issue is? I'm using `zsh` with no issues?

**Comment by rgbkrk** [comment]
I think this may have been fixed in a couple ways:

* We provided sourcing that worked for all shells in the backend
* `carina` the CLI was fixed to be POSIX and Windows compliant

I'm guessing this can be closed. @sjfloat how are things going with `carina` and zsh now?
