### ISSUE TITLE
GUI shows 3 nodes/segments, docker info shows 2.

### ISSUE THREAD

**Issue by jsindy** [getcarina/feedback#14]
> docker info
Containers: 9
Images: 15
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 2
 c86be0c0-104e-458b-aaed-f6fa9437a903-n1: 172.99.77.13:42376
  └ Containers: 5
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 4 GiB / 4.2 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.18.21-1-rackos, operatingsystem=Debian GNU/Linux 7 (wheezy) (containerized), storagedriver=aufs
 c86be0c0-104e-458b-aaed-f6fa9437a903-n2: 172.99.77.14:42376
  └ Containers: 4
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 4 GiB / 4.2 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.18.21-1-rackos, operatingsystem=Debian GNU/Linux 7 (wheezy) (containerized), storagedriver=aufs
CPUs: 24
Total Memory: 8.4 GiB
Name: 373a9be2ea15

GUI shows 3 nodes green.

**Comment by ktbartholomew** [comment]
@jsindy if possible, could you use the dev tools in your browser to inspect the JSON coming back from the API? (`GET /api/clusters`). This will help us figure out whether this is a UI bug or a bug with the upstream API it uses.

**Comment by thomasem** [comment]
Cluster name is `test01`, for reference.

**Comment by jsindy** [comment]
"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title data-rcs-page-title>Carina by Rackspace - BETA</title>
  <link rel="stylesheet" href="/dist/css/base.css?d7bdb7eb15fc243b7df68f7829e57cc1">
  <link rel="stylesheet" href="/dist/css/app.css?d7bdb7eb15fc243b7df68f7829e57cc1">
</head>
<body>
  <div id="app" data-ui-view="rcs"></div>
  <script src="/dist/js/app.bundle.js?d7bdb7eb15fc243b7df68f7829e57cc1"></script>
</body>
</html>"

**Comment by ktbartholomew** [comment]
![image](https://cloud.githubusercontent.com/assets/3018940/10896083/514f6bcc-817d-11e5-8ce3-df9b32b6b290.png)

It looks like make-swarm-app was reporting that the cluster had 5 nodes (after quota was expanded), but `docker info` was still reporting only 2 nodes. Rebuilding the swarm cluster via the rebuild action resulted in `docker info` showing 5 nodes as expected.

**Comment by thomasem** [comment]
Wondering if this issue goes away with Swarm v1.0, but looking at logs, it seems like the discovery mechanism is breaking down somewhere between the agent and the master. I realize that may seem obvious, but the point is that the infrastructure came online as expected, and the traffic started flowing to inform the Swarm manager of the new node.

**Comment by mdarby** [comment]
It appears that this has been resolved.

![desktop 2016-03-29 14-35-52](https://cloud.githubusercontent.com/assets/2805/14119324/a1cdc4ec-f5bb-11e5-827e-cbaa86ebf34c.png)
