### ISSUE TITLE
Service discovery with registrator fails.

### ISSUE THREAD

**Issue by ping-identity** [getcarina/feedback#15]
jsindy$ docker run -d --name registrator -e affinity:container!=registrator* -v /var/run/docker.sock:/tmp/docker.sock:ro gliderlabs/registrator:latest consul://172.99.77.13:8500
60bbbda60681928ad7dd775da266bb49c25ce558c7d4c0fd5d00a8ab407719d4
Error response from daemon: Cannot start container 60bbbda60681928ad7dd775da266bb49c25ce558c7d4c0fd5d00a8ab407719d4: [8] System error: permission denied

registrator reads from the docker socket to populate consul. I am really curious if mounting docker.socket will be permitted. Thanks!

**Comment by jsindy** [comment]
Container starts now but throws the error "dial unix /tmp/docker.sock: connection refused"

Tried the container with --privileged and got "[8] System error: operation not permitted"

Here is the issue on the Registrator side. https://github.com/gliderlabs/registrator/issues/35

Basically what this program does is watch the docker.socket and register services into consul.
https://github.com/gliderlabs/registrator

**Comment by everett-toews** [comment]
Using `--privileged` is currently disabled for security purposes. See:

* https://getcarina.com/docs/faq/#how-are-you-currently-preventing-containers-running-in-privileged-mode
* https://getcarina.com/docs/tutorials/docker-swarm-carina/#privileged-and-capability-run-flags

**Comment by jsindy** [comment]
Registrator is now working mounting with "-v /var/run/docker.sock:/tmp/docker.sock:ro"

On the monster-test cluster

./docker-1.8.2 run -d --restart=always -m 64m --name registrator -e affinity:container!=registrator* -v /var/run/docker.sock:/tmp/docker.sock:ro gliderlabs/registrator:latest -ip $IPofHOST consul://$ip-of-consul-master:8500

**Comment by everett-toews** [comment]
@ping-identity Care to give your run another try and we can potentially close this issue?

**Comment by jsindy** [comment]
@everett-toews , the ping-identity account was me. Good to close.

**Comment by everett-toews** [comment]
:+1:
