### ISSUE TITLE
document what happens to a container when the host dies?

### ISSUE THREAD

**Issue by diwu1989** [getcarina/feedback#16]
If the host machine dies, what guarantees do we have about the container?

**Comment by lauracly** [comment]
Hi there - this is on our "to do" list for our next round of article updates. Haven't decided if it is a stand alone article, or can be included in general troubleshooting; but we will add it and make it easy to find.  Thanks for the feedback.

**Comment by kenperkins** [comment]
This was [implemented recently](https://github.com/getcarina/getcarina.com/pull/632):

> Also, because your Docker containers run inside segments, if a segment dies your container will likewise disappear. This underscores the idea of a container being extremely ephemeral and typically not a good choice for permanent data storage.

https://getcarina.com/docs/concepts/docker-swarm-carina/#carina-segments
