### ISSUE TITLE
TOC needed for FAQ

### ISSUE THREAD

**Issue by simonjj** [getcarina/feedback#17]
The FAQ is difficult to read/consume for people. We may want to have a TOC at the top. This plugins [1] would make this easier.

[1]: https://github.com/dafi/jekyll-toc-generator

**Comment by kenperkins** [comment]
fwiw I can't find the FAQ anywhere. When I google search for it, the link returns 404.

https://getcarina.com/docs/reference/faq/

**Comment by everett-toews** [comment]
@kenperkins See https://github.com/getcarina/getcarina.com/issues/608

**Comment by everett-toews** [comment]
Closed in favour of https://github.com/getcarina/getcarina.com/issues/615
