### ISSUE TITLE
scaling down segment

### ISSUE THREAD

**Issue by diwu1989** [getcarina/feedback#18]
I think it used to be possible to scale down the number of segments, how come it's no longer possible?

**Comment by jnoller** [comment]
Heya! Actually we haven't supported scaling down yet. I'm assuming you want to do this yourself via the CLI/UI (remove segments) vs having it happen automatically

**Comment by diwu1989** [comment]
yeah I want to be able to remove segments

**Comment by ktbartholomew** [comment]
Duplicate of https://github.com/getcarina/feedback/issues/6
