### ISSUE TITLE
FAQ: what is the storage mechanism?

### ISSUE THREAD

**Issue by diwu1989** [getcarina/feedback#20]
Is it instance storage on the local node? Is it SSD?
What's the availability and performance characteristics of a data volume?

**Comment by simonjj** [comment]
these are currently spinning disks, Enterprise SATA, and you get 20GB per segment

**Comment by kenperkins** [comment]
@lauracly we should add a note about this on our FAQs.

**Comment by dalanmiller** [comment]
:+1: to adding to the FAQs. What kind of reliability do I have for storing information in a container?

**Comment by mdarby** [comment]
FAQ merged
