### ISSUE TITLE
Multi host networking via Docker >= 1.9.0

### ISSUE THREAD

**Issue by wiilinkpds** [getcarina/feedback#21]
Will you use new networking features (network overlay driver, network management...) in next Carina release ?

**Comment by rgbkrk** [comment]
We just shipped with Docker 1.9, Swarm 1.0, and are still feeling out all of the nuances with overlay networking. Since swarm relies on overlay networks, you won't be able to use the local isolated networks either.

**Comment by ktbartholomew** [comment]
@wiilinkpds As of February 15, 2016, new clusters are created with Swarm 1.10, including overlay networking capabilities using a bundled Consul cluster. Here's more info on the release: https://getcarina.com/blog/overlay-networks/
