### ISSUE TITLE
Login page (incorrectly?) claims two-factor auth doesn't work

### ISSUE THREAD

**Issue by lvh** [getcarina/feedback#23]
When logging in, the login page claimed 2FA wouldn't work. I logged in with my Rackspace Cloud account, and got a 2FA code as expected.

<img width="510" alt="screen shot 2015-11-16 at 10 20 34 am" src="https://cloud.githubusercontent.com/assets/97816/11187531/6f078882-8c4c-11e5-8fa7-74b972d97af8.png">

Is this only the case when creating a new account or something?

**Comment by jnoller** [comment]
That's a bug; we support 2fa for existing Rackspace users, but not on new signups

**Comment by rgbkrk** [comment]
Text updated, @ktbartholomew [shipped 2FA for existing users last week](https://getcarina.com/blog/weekly-news-docker-1-9-dvm/#app-getcarina-com-updates).
