### ISSUE TITLE
swarm lost a node

### ISSUE THREAD

**Issue by elephantfries** [getcarina/feedback#24]
I have a three node carina cluster. After starting a container on node2, swarm lost it and does not report its existence.  I know it does exist because I just happen to be running a container interactively on it.  I also know the container that was started on it runs just fine because its service (mariadb) is available at that node's internal IP address.  [No I did not remove any swarm containers]

Here's what docker info reports (incorrectly showing only two nodes):

waldemar@iris:~/chest/carina$ docker info
Containers: 7
Images: 10
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 0658c03c-7925-488a-8c04-51b5c7329205-n1: 172.99.78.186:42376
  └ Containers: 4
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 0 B / 4.2 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.18.21-1-rackos, operatingsystem=Debian GNU/Linux 7 (wheezy) (containerized), storagedriver=aufs
 0658c03c-7925-488a-8c04-51b5c7329205-n3: 172.99.78.184:42376
  └ Containers: 3
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 0 B / 4.2 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.18.21-1-rackos, operatingsystem=Debian GNU/Linux 7 (wheezy) (containerized), storagedriver=aufs
CPUs: 24
Total Memory: 8.4 GiB
Name: 286ba8d1c703

**Comment by thomasem** [comment]
Seeing a whole lot of nodes being lost and then re-registered in the manager logs on this cluster:

```
time="2015-11-23T12:01:27Z" level=info msg="Removed Engine 0658c03c-7925-488a-8c04-51b5c7329205-n3"
time="2015-11-23T12:02:07Z" level=info msg="Registered Engine 0658c03c-7925-488a-8c04-51b5c7329205-n3 at 172.99.78.184:42376"
time="2015-11-23T12:02:27Z" level=info msg="Registered Engine 0658c03c-7925-488a-8c04-51b5c7329205-n1 at 172.99.78.186:42376"
time="2015-11-23T12:06:34Z" level=error msg="Discovery error: Failed to fetch entries, Discovery service returned 500 HTTP status code"
time="2015-11-23T12:18:27Z" level=info msg="Removed Engine 0658c03c-7925-488a-8c04-51b5c7329205-n1"
time="2015-11-23T12:20:27Z" level=info msg="Registered Engine 0658c03c-7925-488a-8c04-51b5c7329205-n1 at 172.99.78.186:42376"
time="2015-11-23T12:21:47Z" level=info msg="Removed Engine 0658c03c-7925-488a-8c04-51b5c7329205-n1"
time="2015-11-23T12:23:27Z" level=info msg="Registered Engine 0658c03c-7925-488a-8c04-51b5c7329205-n1 at 172.99.78.186:42376"
time="2015-11-23T12:44:27Z" level=info msg="Removed Engine 0658c03c-7925-488a-8c04-51b5c7329205-n2"
time="2015-11-23T12:45:07Z" level=info msg="Registered Engine 0658c03c-7925-488a-8c04-51b5c7329205-n2 at 172.99.78.185:42376"
time="2015-11-23T12:46:07Z" level=info msg="Removed Engine 0658c03c-7925-488a-8c04-51b5c7329205-n1"
time="2015-11-23T12:47:47Z" level=info msg="Registered Engine 0658c03c-7925-488a-8c04-51b5c7329205-n1 at 172.99.78.186:42376"
time="2015-11-23T12:52:47Z" level=info msg="Removed Engine 0658c03c-7925-488a-8c04-51b5c7329205-n1"
time="2015-11-23T12:54:47Z" level=info msg="Registered Engine 0658c03c-7925-488a-8c04-51b5c7329205-n1 at 172.99.78.186:42376"
time="2015-11-23T12:57:14Z" level=error msg="Discovery error: Failed to fetch entries, Discovery service returned 500 HTTP status code"
time="2015-11-23T13:06:57Z" level=info msg="Removed Engine 0658c03c-7925-488a-8c04-51b5c7329205-n3"
time="2015-11-23T13:08:47Z" level=info msg="Registered Engine 0658c03c-7925-488a-8c04-51b5c7329205-n3 at 172.99.78.184:42376"
time="2015-11-23T13:24:07Z" level=info msg="Removed Engine 0658c03c-7925-488a-8c04-51b5c7329205-n3"
time="2015-11-23T13:24:27Z" level=info msg="Registered Engine 0658c03c-7925-488a-8c04-51b5c7329205-n3 at 172.99.78.184:42376"
time="2015-11-23T13:27:27Z" level=info msg="Removed Engine 0658c03c-7925-488a-8c04-51b5c7329205-n2"
time="2015-11-23T13:29:10Z" level=info msg="Registered Engine 0658c03c-7925-488a-8c04-51b5c7329205-n2 at 172.99.78.185:42376"
time="2015-11-23T13:30:21Z" level=info msg="Removed Engine 0658c03c-7925-488a-8c04-51b5c7329205-n2"
time="2015-11-23T13:30:21Z" level=info msg="Removed Engine 0658c03c-7925-488a-8c04-51b5c7329205-n3"
time="2015-11-23T13:30:47Z" level=info msg="Registered Engine 0658c03c-7925-488a-8c04-51b5c7329205-n2 at 172.99.78.185:42376"
time="2015-11-23T13:31:07Z" level=info msg="Registered Engine 0658c03c-7925-488a-8c04-51b5c7329205-n3 at 172.99.78.184:42376"
time="2015-11-23T13:49:37Z" level=info msg="Removed Engine 0658c03c-7925-488a-8c04-51b5c7329205-n3"
time="2015-11-23T13:49:47Z" level=info msg="Registered Engine 0658c03c-7925-488a-8c04-51b5c7329205-n3 at 172.99.78.184:42376"
```

**Comment by thomasem** [comment]
It appears that your node is back and registered with the cluster. We're looking into this. Please let us know of any other incidents.

Thanks!

**Comment by elephantfries** [comment]
Yes, it's back.  I can see swarm containers did not restart so it just magically recovered.  What discovery service is carina using for swarm?  Is it consul by any chance?  If so, I think I have a theory of what might have happened.

**Comment by thomasem** [comment]
Haha, yeah. This is new behavior since Swarm 1.0.0, from what I can tell. In 0.4.0, however, new nodes had a hard time joining the cluster after some period of time (one we never determined). By hard time, I mean, they never showed up. :) We had to restart the manager to unwedge the situation, usually.

The Swarm's from Carina are using the public discovery mechanism at the moment.

**Comment by elephantfries** [comment]
The reason I mentioned consul is because, in my own tests, I have seen it returning 'no leader' sometimes even if everything was perfectly fine. It was also failing DNS resolution from time to time most likely for the same reason.  It seems like some raft protocol timeouts are so tight that they can be exceeded even on a shared LAN. It was especially frequent with VMs. The speculation is that VMs may be holding packets in queues just long enough to cause trouble.  I've never seen anything like that with etcd which is why I tend to go with etcd whenever possible. Etcd would hold for an extended time on occasion, even several seconds, but it would not return a protocol failure.

**Comment by thomasem** [comment]
Iiiiinteresting. I didn't know that about Consul. This is great feedback. I'll keep an eye out for this, especially as we look at Consul (and other alternatives) for discovery.

**Comment by elephantfries** [comment]
So I am getting those swarm outages continuously. They are usually short lived, a minute or so and swarm is back.  I was working on my website and I saw it happen three times over a span of five hours or so.

**Comment by thomasem** [comment]
Did a little poking around, seems like this issue: https://github.com/docker/swarm/issues/1405.

**Comment by thomasem** [comment]
We're in the process of looking at decentralizing service discovery to the cluster itself. Please stay tuned! :)

**Comment by elephantfries** [comment]
Yes, this looks very much like 1405 if carina is using tokens from docker or some other 'centralized' service. I would be happy to test 'decentralized' discovery, especially it could be made available as part of the service.  Otherwise, it would seem I'd need to overlay my own discovery service. [which I might do anyway but at least there would be choice]

**Comment by everett-toews** [comment]
We now have our own discover service, read [Use overlay networks in Carina](https://getcarina.com/docs/tutorials/overlay-networks/) for more info.
