### ISSUE TITLE
Killing all containers nukes cluster

### ISSUE THREAD

**Issue by rosskukulinski** [getcarina/feedback#25]
So I decided to kill all of my containers in a cluster and it seems to have killed a docker daemon or something.

```
[~/dev/yodlr/compose]$ docker kill $(docker ps -a -q)
e2c63430d573
52b84f145f48
786ff9cc5043
381734a7d3a4
253aad491265
310c6ab68d75
4f7103adedfa
c339a0e7364e
An error occurred trying to connect: Post https://172.99.70.4:2376/v1.20/containers/3e6277829136/kill?signal=KILL: EOF
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

I get the same error, ```Cannot connect to the Docker daemon. Is 'docker -d' running on this host?``` if I run ```docker info``` or ```docker ps```.

I'm not sure how to fix/repair the cluster...

**Comment by simonjj** [comment]
You likely deleted your management containers @rosskukulinski. Have you tried rebuilding the cluster? As shown here: [https://getcarina.com/docs/faq/#what-does-the-cluster-rebuild-action-do](https://getcarina.com/docs/faq/#what-does-the-cluster-rebuild-action-do)?

**Comment by rosskukulinski** [comment]
thanks @simonjj.  Rebuilding the cluster brought things back to life.
