### ISSUE TITLE
Easier identification of segment IPs

### ISSUE THREAD

**Issue by rosskukulinski** [getcarina/feedback#26]
It's currently a bit of an ordeal to get the ServiceNet IP of a segment (or for all 3...).  I'm going through [your servicenet doc](https://getcarina.com/docs/tutorials/servicenet/) which does work... but its arduous.

I know you're probably hindered by poor Docker tooling, but its something that would help until you've got overlay networking and/or private networks (w/ overlay) fully functional.

**Comment by thomasem** [comment]
Yep. Totally agree, and you pretty much described the constraints we have right now. We're looking into overlay support for this and other reasons. :)

**Comment by rosskukulinski** [comment]
should be resolved with network overlay
