### ISSUE TITLE
Does cpu_set work?

### ISSUE THREAD

**Issue by rosskukulinski** [getcarina/feedback#27]
I'm just wondering if the cpuset docker run / docker-compose configuration have any effect?

**Comment by thomasem** [comment]
So far, we've seen that this runs as expected: https://hub.docker.com/r/agileek/cpuset-test/. But, we haven't had a good opportunity for how this is affected by multi-tenancy and resource contention scenarios yet. Would be very interested if you find anything around the CPU flags.
