### ISSUE TITLE
Gravatars broken on community.getcarina.com

### ISSUE THREAD

**Issue by everett-toews** [getcarina/feedback#28]

**Comment by kenperkins** [comment]
This appears to no longer reproduce.

**Comment by everett-toews** [comment]
Yesterday I noticed that Gravatars were fixed but uploading your own image still resulted in a broken image icon.

**Comment by mdarby** [comment]
yep; sorry circling back to this -- gravatars are fixed and wasn't aware of image uploading issues. I've the shared asset uploads going to AWS on a personal card ATM.

**Comment by kenperkins** [comment]
Does discourse not support Cloud Files/Swift? Sounds like a PR waiting to happen :)

**Comment by mdarby** [comment]
It doesn't unfortunately. I discussed with the team and considering the options we just went AWS :)

**Comment by kenperkins** [comment]
Having discourse support Cloud Files is certainly orthogonal to this issue. It's more of a broader DevEx idea :)
