### ISSUE TITLE
Carina logo on https://community.getcarina.com

### ISSUE THREAD

**Issue by ReneeRendon** [getcarina/feedback#3]
On https://community.getcarina.com/, when you click the Carina icon, should it take you back to the home page? It seems like it should. It does from the https://getcarina.com/docs/ page. 
Once readers go to the Community page, they have no way on the page to navigate home

**Comment by rgbkrk** [comment]
I've noticed that Hotel California effect too.

**Comment by mdarby** [comment]
Sorry for the _massive_ delay.

![carina forums 2016-03-29 12-54-13](https://cloud.githubusercontent.com/assets/2805/14116362/5ddad210-f5ad-11e5-8504-38a36a5daf76.png)

**Comment by rgbkrk** [comment]
Looks awesome!
