### ISSUE TITLE
ssl_error_bad_cert_domain for status.getcarina.com

### ISSUE THREAD

**Issue by simonjj** [getcarina/feedback#30]
seems like there's a cert conflict between status.getcarina.com and carinabyrackspace.statuspage.io.

**Comment by rgbkrk** [comment]
Our site uses HSTS (HTTP Strict Transport Security), which means that the SNI on carinabyrackspace.statuspage.io is not going to work because of our domain level settings.

**Comment by rosskukulinski** [comment]
FYI, this is till true.  I got an email notification about the dashboard outage and went to status.getcarina.com and got the SSL bad cert domain.  Unable to click through since HTST is enabled.

**Comment by jnoller** [comment]
This has been resolved! https://status.getcarina.com/ should now be on the proper cert chains.

**Comment by rosskukulinski** [comment]
Confirmed working, thanks @jnoller
