### ISSUE TITLE
Running a heavy load test on Drupal Cluster induces "Error State"

### ISSUE THREAD

**Issue by jnoller** [getcarina/feedback#34]
Cluster becomes unavailable - error state. Rebuild does not work / etc. When this occurred it required a host reboot. 

We'll need to get the dockerfile and perform a load test.

**Comment by sourcejockey** [comment]
Here's how I set it all up.

Build files:
[haproxy.zip](https://github.com/getcarina/feedback/files/86539/haproxy.zip)

# docker create --name data --volume /var/lib/mysql mysql:5.6 /bin/true
# docker run --detach --restart=always --name mysql56 --env MYSQL_ROOT_PASSWORD=*** --env MYSQL_DATABASE=*** --env MYSQL_USER=*** --env MYSQL_PASSWORD=*** --volumes-from data mysql:5.6
# docker create --name webvolume --volume /var/www/ --volume /etc/apache2 --volume /etc/ssl drupal /bin/true
# docker run --detach --restart=always --name drupal --link mysql56:mysql -p 80:80 -p 443:443 --volumes-from webvolume drupal
# docker run --detach --restart=always --name drupal_01 --link mysql56:mysql --volumes-from webvolume drupal && docker run --detach --restart=always --name drupal_02 --link mysql56:mysql --volumes-from webvolume drupal && docker run --detach --restart=always --name drupal_03 --link mysql56:mysql --volumes-from webvolume drupal && docker run --detach --restart=always --name drupal_04 --link mysql56:mysql --volumes-from webvolume drupal
# docker run --name haproxy --link drupal_01:drupal_01 --link drupal_02:drupal_02 --link drupal_03:drupal_03 --link drupal_04:drupal_04 --detach -p 80:80 -p 443:443 haproxy

**Comment by everett-toews** [comment]
Tracking this in https://github.com/getcarina/feedback/issues/36
