### ISSUE TITLE
Can't get activation email or reset password email

### ISSUE THREAD

**Issue by pjperez** [getcarina/feedback#35]
Hi there!

Signed up a few hours ago and didn't get the activation email. My email address is on the domain "wormhole.network", so I thought that might be the problem!

Tried to login without activating my account, but of course didn't work either :) :)

I'm not in a hurry, but really willing to try Carina. So if you find the issue please let me know if I have to do anything from side.

**Comment by pjperez** [comment]
This has been solved now on IRC. Thank you.

**Comment by ktbartholomew** [comment]
For posterity: The customer's email host was rejecting the activation message because the client IP (A mailgun server IP) was on a Spamhaus block list:

> 550 5.7.1 Service unavailable; Client host [184.173.153.61] blocked using Spamhaus; To request removal from this list see http://www.spamhaus.org/lookup.lasso
