### ISSUE TITLE
OAuth Support?

### ISSUE THREAD

**Issue by carolynvs** [getcarina/feedback#39]
If Carina had oauth support, that would really open up some interesting possibilities for integrating with Carina. What I would like to use it for is this: 

1. User logs into my site using Carina oauth.
2. I make a cluster for them on their Carina account, and setup an application on their cluster.
3. User magically has a working setup without having to touch docker, read my documentation, etc.

Right now my prototype has them log in with their Carina username and api key. It would be preferable they could simply grant me limited access without giving away their Carina api key, which may also have access to their entire Rackspace Cloud account. @betatim is doing something similar by having them upload their cluster credentials zip.

**Comment by rgbkrk** [comment]
YES YES YES

**Comment by rgbkrk** [comment]
As in I want that too.

**Comment by betatim** [comment]
I'm just here to say: me too!

**Comment by mdarby** [comment]
I'll have to dig back in but I think that's doable actually :)

**Comment by betatim** [comment]
:rocket:
