### ISSUE TITLE
GetCarina persistant log in upon selecting 'Community & Feedback'

### ISSUE THREAD

**Issue by nicolewillis** [getcarina/feedback#4]
Upon logging into GetCarina with credentials, it shows that I am logged in (see screen shot attached).  After selecting 'Community & Feedback' it appears that I am then logged out, as the 'Login' option re-appears (see screenshot) and its unclear how to get back 'Home'.
![screen shot 2015-10-28 at 10 09 06 am](https://cloud.githubusercontent.com/assets/15364422/10793077/590801a4-7d5d-11e5-9a0c-403e7924782b.png)
![screen shot 2015-10-28 at 10 09 20 am](https://cloud.githubusercontent.com/assets/15364422/10793078/591aec6a-7d5d-11e5-902d-b21b0bc9d85f.png)

**Comment by rgbkrk** [comment]
Definitely bugs on our part here.

We don't have true single sign on yet, so you're stuck logging into both discourse (software backing the forums) and the control panels. As for there not being a way to get back to the control panel, we need to add that to the header on discourse (also reported in #3).

Thanks for trying Carina out!

**Comment by mdarby** [comment]
I've added header links to Discourse.
