### ISSUE TITLE
Packet loss issues to cluster

### ISSUE THREAD

**Issue by jnoller** [getcarina/feedback#42]
See: https://community.getcarina.com/t/troubleshooting-packet-loss/118

Hello Carina Team,

We are loving the platform plenty and we are having a great beta experience with Carina - unfortunately our test cluster is constantly subject to packet loss at the second hop (104.130.0.2 in our path) without any clear relation to the container application or status. Discussing with other Carina testers this seems to be an isolated issue so far - I am wondering if there is anything useful we could try other than drop/recreate the cluster?

Here's an example barely pinging the Google DNS servers:

PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: icmp_seq=0 ttl=43 time=9.002 ms
64 bytes from 8.8.8.8: icmp_seq=1 ttl=43 time=8.958 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=43 time=8.955 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=43 time=8.959 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=43 time=8.969 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=43 time=8.963 ms
64 bytes from 8.8.8.8: icmp_seq=6 ttl=43 time=8.725 ms
64 bytes from 8.8.8.8: icmp_seq=7 ttl=43 time=8.858 ms
64 bytes from 8.8.8.8: icmp_seq=8 ttl=43 time=8.785 ms
64 bytes from 8.8.8.8: icmp_seq=9 ttl=43 time=8.971 ms
64 bytes from 8.8.8.8: icmp_seq=10 ttl=43 time=8.952 ms
64 bytes from 8.8.8.8: icmp_seq=31 ttl=43 time=9.015 ms
64 bytes from 8.8.8.8: icmp_seq=32 ttl=43 time=8.927 ms
64 bytes from 8.8.8.8: icmp_seq=33 ttl=43 time=8.944 ms
64 bytes from 8.8.8.8: icmp_seq=34 ttl=43 time=8.988 ms
64 bytes from 8.8.8.8: icmp_seq=35 ttl=43 time=8.974 ms
64 bytes from 8.8.8.8: icmp_seq=36 ttl=43 time=8.960 ms
64 bytes from 8.8.8.8: icmp_seq=37 ttl=43 time=8.967 ms
64 bytes from 8.8.8.8: icmp_seq=38 ttl=43 time=8.851 ms
64 bytes from 8.8.8.8: icmp_seq=39 ttl=43 time=8.943 ms
64 bytes from 8.8.8.8: icmp_seq=40 ttl=43 time=8.980 ms
64 bytes from 8.8.8.8: icmp_seq=41 ttl=43 time=8.920 ms
64 bytes from 8.8.8.8: icmp_seq=42 ttl=43 time=8.987 ms
64 bytes from 8.8.8.8: icmp_seq=43 ttl=43 time=8.829 ms
64 bytes from 8.8.8.8: icmp_seq=44 ttl=43 time=8.975 ms
64 bytes from 8.8.8.8: icmp_seq=45 ttl=43 time=8.980 ms
64 bytes from 8.8.8.8: icmp_seq=62 ttl=43 time=9.113 ms
64 bytes from 8.8.8.8: icmp_seq=63 ttl=43 time=8.978 ms
64 bytes from 8.8.8.8: icmp_seq=64 ttl=43 time=8.942 ms
64 bytes from 8.8.8.8: icmp_seq=65 ttl=43 time=8.967 ms
64 bytes from 8.8.8.8: icmp_seq=66 ttl=43 time=8.957 ms
^C--- 8.8.8.8 ping statistics ---
67 packets transmitted, 31 packets received, 53% packet loss
round-trip min/avg/max/stddev = 8.725/8.945/9.113/0.070 ms

Thanks in advance!

filing for @lmangani

**Comment by lmangani** [comment]
Thanks @jnoller did not realize i should raise it here

**Comment by mendeni** [comment]
This issue has been resolved as a result our network incident maintenance.
Please let us know if you continue to see similar packet loss behavior.

**Comment by lmangani** [comment]
Thanks @jnoller @mendeni cluster rebuilt and issue gone - go Carina!
