### ISSUE TITLE
Problem getting SMS text to confirm my account

### ISSUE THREAD

**Issue by THernandez03** [getcarina/feedback#44]
I haven't been received the SMS to confirm my account. I tried different formats but it doesn't work.

* From: Chile (+56)

**Comment by zhangshaocong258** [comment]
me too

**Comment by everett-toews** [comment]
Handled over in [Problem getting SMS text to confirm my account](https://community.getcarina.com/t/problem-getting-sms-text-to-confirm-my-account/133)

**Comment by zhangshaocong258** [comment]
use USA number in the Internet ,it is free
