### ISSUE TITLE
Cant create clusters.

### ISSUE THREAD

**Issue by Fillerix99** [getcarina/feedback#47]
I just get an red error when trying to create my clusters.

**Comment by jnoller** [comment]
Can you drop an email to jesse.noller@rackspace.com with the account email/username included so we can debug?

**Comment by ardecvz** [comment]
Hi,

the same problem with cluster creating so it may be a good time to update the status page ;)

My account on Carina is ardecvz@gmail.com.

Thanks!

**Comment by jnoller** [comment]
thanks for letting us know - we've posted this to the status page. @Fillerix99 I've also dropped an email to your gmail address for an account followup.
