### ISSUE TITLE
Push-based deployment

### ISSUE THREAD

**Issue by jamiehannaford** [getcarina/feedback#52]
1. Research current solutions that allows push-based deployment of containers when their base image is updated

2. If no current solution works, write a small script (probably in Go) that can be executed in a Docker container. Most of [watchtower's](https://github.com/getcarina/watchtower) logic can be reused.

**Comment by everett-toews** [comment]
I believe this is being tracked in https://github.com/getcarina/getcarina.com/issues/817 now. Please reopen if I'm wrong about that.
