### ISSUE TITLE
Intermediate images are not found when debugging a build from a Dockerfile

### ISSUE THREAD

**Issue by ionrock** [getcarina/feedback#53]
When creating an image from a Dockerfile there may be an error. If you are interested in debugging the problem (ie run a shell in the container and see what the issue is) you can use the image hex. On carina, this image hex is reported as no found as it looks to the library repo instead. See below for an example. 

    # Taken from a failed Dockerfile build
     ---> Running in 3f584cd3c831
    /bin/sh: 1: /etc/init.d/mysql-server: not found
    The command '/bin/sh -c /etc/init.d/mysql-server start &&     mysql -i < setup_databases.sql' returned a non-zero code: 127
    $ docker run --rm -it 3f584cd3c831 /bin/bash
    docker run --rm -it 3f584cd3c831 /bin/bash
    Error response from daemon: Error: image library/3f584cd3c831 not found

One work around is to simply comment out the parts of the Dockerfile and build a temp image:

```bash
$ cat Dockerfile
FROM ubuntu:14.04

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN apt-get update && apt-get install -y wget
$ docker build -t testing-intermediate-images .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu:14.04
 ---> 07c86167cdc4
Step 2 : RUN wget https://bootstrap.pypa.io/get-pip.py
 ---> Running in 0eeb7c8647f3
/bin/sh: 1: wget: not found
The command '/bin/sh -c wget https://bootstrap.pypa.io/get-pip.py' returned a non-zero code: 127
$ docker run --rm -it 0eeb7c8647f3 /bin/bash
Error response from daemon: Error: image library/0eeb7c8647f3 not found
$ cat Dockerfile
FROM ubuntu:14.04

# RUN wget https://bootstrap.pypa.io/get-pip.py
# RUN apt-get update && apt-get install -y wget
$ docker build -t testing-intermediate-images .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu:14.04
 ---> 07c86167cdc4
Successfully built 07c86167cdc4
$ docker run --rm -it testing-intermediate-images /bin/bash
root@6e5b970efcc9:/# exit
```

**Comment by dimtruck** [comment]
@ionrock How about   --force-rm=false  on docker build?

**Comment by coreypobrien** [comment]
It sounds like you're looking for is the --rm flag for docker.
> If you wish to keep the intermediate containers after the build is complete, you must use --rm=false. This does not affect the build cache.
