### ISSUE TITLE
[Discussion] Revert back to node vs. segment terminology

### ISSUE THREAD

**Issue by jnoller** [getcarina/feedback#54]
Prior to launch, I pushed on the segment terminology because of the internal architecture of Carina:

- https://github.com/getcarina/getcarina.com/pull/674
- https://github.com/getcarina/getcarina.com/issues/460

As @rosskukulinski cites in #https://github.com/getcarina/getcarina.com/issues/460#issuecomment-158549110 it's confusing, especially as the secure multi tenant nature of the data plane is an implementation detail leaking into the UX.

When we look towards supporting other things such as bays/kubernetes this begins to get even worse - in k8s you get pods/nodes/masters/minions and so on. For swarm the lowest common entity is a 'node' regardless of **where it lives**.

Unfortunately this is where my background / distributed systems background triggered effectively exposing internal details that aren't topical to the ecosystem and pushing the cognitive burden to the user.

Suggestions? Do we keep segments, or move to the standard terminology for swarn / k8s / etc?

**Comment by jnoller** [comment]
See:

- https://getcarina.com/docs/concepts/docker-swarm-carina/
- https://getcarina.com/docs/overview-of-carina/

For the implementation detail we're exposing. Of interest is:

![image](https://cloud.githubusercontent.com/assets/51528/13846958/95191550-ec18-11e5-9d31-27f489189010.png)

**Comment by jnoller** [comment]
In swarm land a node is a swarm host, and the locality / scheduling is simply based on the swarm node (cluster) ergo you could have many swarm nodes on a single box. This is 'bad application design' for horizontal scale out and fault tolerance but also what the docker community has baked into the nomenclature.

**Comment by jnoller** [comment]
In Carina a cluster is $n swarm nodes sharing the same certificates. It's therefore logical that a segment could be on libvrt/lxc and another on a VM, or physical host

**Comment by lblackstone** [comment]
I'd be in favor of switching to "node". This was confusing to me as well as I was recently learning the product. Magnum also refers to those entities as "nodes", which was the main source of my initial confusion.

**Comment by smashwilson** [comment]
I'm :+1: on using "nodes". In my experience explaining Carina to devs it's been the number one eyebrow-raising "wait, what? oh, whatever" moment.

The Docker client and all of the Swarm docs use the "nodes" terminology. Using a different term for the same concept introduces an unnecessary disconnect and forces users to translate mentally between their tooling and our documentation and UI.

**Comment by jnoller** [comment]
I put the cognitive burden on the end user 

![image](https://cloud.githubusercontent.com/assets/51528/13847393/0bcf84f2-ec1b-11e5-9fff-5213b5f19ed5.png)

**Comment by ogrisel** [comment]
I would also go for the "node" terminology. But if I understand correctly, all the nodes / segments of a carina "cluster" are provisioned on the same physical host at the moment? I think this should be made more explicit. Usually the term "cluster" is interpreted as a collection of physical hosts.

Are there any plan to have clusters with several physical hosts in a later version of carina?

**Comment by jnoller** [comment]
@ogrisel Yes, hence why I bring it up - a segment is a node in a cluster regardless of physical location (in swarm and k8s terminology). The underlying host / machine is an implementation detail determined by a user's need for resiliency, isolation or security / latency.

- Current state: all clusters are not physically disparate (nodes are all on the same physical host)
- Future state: nodes or clusters could span $n physical / virtual hosts

Whats worse is that for the existing docker/k8s communities they have standardized on the node/cluster terminology without dictating physical isolation for reliability and consensus within things like etcd, and so on.

**Comment by ogrisel** [comment]
Thanks for the clarification. +1 for node still. It would be great to expose resiliency hints to the docker API in some way are another. E.g. being able to tell that container that run `glusterfs` or `cassandra` workers should run on different physical nodes with different disks for instance. But I guess this is more an issue of docker swarm than an issue of carina itself.

**Comment by jnoller** [comment]
@ogrisel Bingo. It's a scheduling optimization handles by k8s but not swarm (AFAIK)

**Comment by thomasem** [comment]
@jnoller @ogrisel: I'm confused... at the moment Carina nodes in a cluster do have a tendency to be on separate physical hosts. It's not guaranteed, is the snag.

**Comment by jnoller** [comment]
@thomasem Yeah, the 'not guaranteed' is why I pushed for segments vs. nodes - but your right we try to push onto different physical hosts.

**Comment by thomasem** [comment]
I, too, am in favor of using "node" in place of "segment".

**Comment by thomasem** [comment]
@jnoller Ohhh okay. I understand where you're coming from. :) Thanks. Only a Sith deals in absolutes.

**Comment by jnoller** [comment]
By far @everett-toews and @rgbkrk have given the most talks to date, I'd like their input. @mdarby has been leading training.

**Comment by mdarby** [comment]
The node v. segment question comes up each time and I find myself re-explaining it a couple times each training. Nothing massive but it is a point of confusion.

**Comment by bfosberry** [comment]
:+1: :eggplant: :monkey:

**Comment by rgbkrk** [comment]
I want `node`.

> Only a Sith deals in absolutes.

This is how I know that both @thomasem and Obi Wan are Siths.

**Comment by rgbkrk** [comment]
Every single time we do training or talks, we have to communicate Swarm nodes (at the CLI) vs. Carina Segments. It tends to be hard to juggle "two" concepts for people starting out. It also makes our documentation two headed.

**Comment by everett-toews** [comment]
:+1: node 

Every time we have to document some ecosystem tooling that outputs "node" we have to do a little :microphone: and :dancer: and say we actually call that a segment in Carina-land. It's a real paper cut and makes it that much more confusing when using ecosystem tooling.

**Comment by rosskukulinski** [comment]
As I've said before - I think you should call them 'nodes' and then make it so us users don't need to know about your internals.  I would _expect_ you to handle scheduling 'nodes' in a cluster in such a way that they're not on the same physical hosts.  If you can't do that -- you should be explicit about the deficiency.
