### ISSUE TITLE
docker.env doesn't compatible with fish

### ISSUE THREAD

**Issue by 7sDream** [getcarina/feedback#60]
I use fish as my default sh, the current docker.env doesn't compatible with it, see below:

![source docker.env error](http://ww1.sinaimg.cn/large/88e401f0jw1f2ta90407sj20hr04qta7.jpg)

But I don't want switch to bash to run dvm and docker command... could you please add support for fish?

---

As I'm can't wait to use it, I write a [docker.fish](https://gist.github.com/7sDream/4671ac4b6daebd4e7c377b1c83d7a092) for temporary use, it has same function as offical docker.env. Just some convert work, and I don't test all possible station, but it work fine with me(for now)

But I still want the OFFICAL fish support! Thanks for your work!

**Comment by rgbkrk** [comment]
Hey @7sDream!

We'll have to do this in a couple phases:

* [ ] On the backend, create a docker.fish file that is returned in the zip file
* [ ] Within libcarina (go bindings) extract the fish shell script
* [ ] `dvm` needs to support multiple shells, likely relying on `$SHELL`
* [ ] `carina` would also need to rely on `$SHELL` to provide the right output to `carina env clusterName`

/cc @carolynvs I'll get started on the backend bits now.

**Comment by 7sDream** [comment]
Thanks!

Yes, I also notice the dvm has same issue and reported to them, with [my temporary use script](https://github.com/getcarina/dvm/issues/94).

Waiting for your news.

**Comment by rgbkrk** [comment]
Alright @7sDream, here's the current fish shell script I've put together based on yours:

```
set DIR (dirname (status -f))

set -x DOCKER_HOST tcp://%(host_addr)s:2376
set -x DOCKER_TLS_VERIFY 1
set -x DOCKER_CERT_PATH $DIR

set -x DOCKER_VERSION %(docker_version)s
```

Our script for bash/tcsh/dash/zsh was written in such a way that it would be POSIX compliant and work across all the shells (it used to be simplified for bash). Since this one is going to write out `docker.fish`, I was able to trim it down.

Note that I took out `-U` from your script as we want people to be able to run commands against multiple docker endpoints in different terminals.

**Comment by rgbkrk** [comment]
This will only apply to new clusters once shipped. I'll let you know when it is ready - likely won't be today.

**Comment by 7sDream** [comment]
@rgbkrk yes, I use -U because I only have one docker to run, that is a mistake...
Thanks for your work again!

**Comment by rgbkrk** [comment]
All set on the backend:

```
kyle@lack ~/code/src/github.com$ carina credentials test2
#
# Credentials written to "/Users/rgbkrk/.carina/clusters/rgbkrk/test2"
# To see how to connect to your cluster, run: carina env test2
#
kyle@lack ~/code/src/github.com$ ls /Users/rgbkrk/.carina/clusters/rgbkrk/test2
README.md   ca-key.pem  ca.pem      cert.pem    docker.cmd  docker.env  docker.fish docker.ps1  key.pem
kyle@lack ~/code/src/github.com$ fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
kyle@lack ~/c/s/github.com> source /Users/rgbkrk/.carina/clusters/rgbkrk/test2/docker.fish
kyle@lack ~/c/s/github.com> docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
c5427f2b0bf7        carina/consul       "/bin/consul agent -b"   5 minutes ago       Up 2 minutes                            e0549cce-31c4-4096-9d06-8f0c71baa236-n1/carina-svcd
```

Next up is `libcarina` and `carina`

**Comment by carolynvs** [comment]
On the dvm side, we already have a `--shell` argument which is defaulted to `$SHELL`.

**Comment by kimtryce** [comment]
@7sDream Before closing this out we wanted to make sure that we answered all your questions.

**Comment by 7sDream** [comment]
@kimtryce 

Thanks for your work!

It works fine now.

**Comment by kimtryce** [comment]
Glad to hear it!  Closing issue.
