### ISSUE TITLE
Possibility to shrink a cluster?

### ISSUE THREAD

**Issue by zs-zs** [getcarina/feedback#64]
Is it possible to shrink a cluster? I found that issuing negative grow commands using the CLI has a shrink effect on the cluster but is it possible that shrinking doing this way just messes up the cluster - even after a rebuild? 

From the Web UI: _"Nodes can be added, but not removed"_

Probably it's connected to #63.

**Comment by thomasem** [comment]
This is a bug. We ought to be returning a bad request for trying to downscale a cluster. Given the complexities of essentially "de-fragmenting" a cluster, we've opted to not address this, at least until we see how we can leverage something like Kubernetes for re-balancing downscaled clusters.

**Comment by thomasem** [comment]
Thank you! :smile:

**Comment by thomasem** [comment]
So, you did something like `carina grow --by=-1`?

**Comment by thomasem** [comment]
Was able to recreate this issue and have a patch up for fixing, ideally for next release.

**Comment by thomasem** [comment]
Fixed with latest deploy.

**Comment by thomasem** [comment]
Please feel free to re-open if you see this problem again. :)

**Comment by ogrisel** [comment]
@thomasem I have a similar problem from the CLI:

```
$ carina ls
ClusterName         Flavor              Nodes               AutoScale           Status
cluster-1           container1-4G       3                   false               active
$ carina grow --by=-2 cluster-1
carina: error: {"error": "cannot grow a cluster by less than 1 node"}, try --help
$ carina --version
Version: v1.4.0
Commit:  f63790db44677584dc2639f42c7527626039f490
```

**Comment by rgbkrk** [comment]
Looks like the error needs to be parsed out for the user. We can't _actually_ lower the cluster size though we can present this information better.

**Comment by ogrisel** [comment]
I am pretty sure it worked in the past. Maybe this is my imagination.
