### ISSUE TITLE
docker load is failing

### ISSUE THREAD

**Issue by vikomall** [getcarina/feedback#65]
'docker load' is failing with following error message.
=================================
e3d4a2af-31aa-48ae-acd3-ae37cbe300d9-n1: Loading Image... : Post https://x.x.x.x:42376/v1.15/images/load: EOF
FATA[0000] Post https://x.x.x.x:42376/v1.15/images/load: EOF

=================================

Instructions to reproduce the problem:
1. Run 'docker run busybox'
2. Make sure that busybox image is in 'docker images' 
3. Run following command to save the image locally 'docker save busybox > busybox.tar'
4. Now try loading locally stored image 'docker load -i busybox.tar'
This steps results in the above mentioned error

**Comment by vikomall** [comment]
This is blocking issue for us. could some one provide ETA for this?

**Comment by lblackstone** [comment]
Hey @vikomall, I'm currently working on a patch to fix this issue. I'm hoping to have it tested and ready to deploy early next week. Docker fixed this bug in v1.11, and I'm backporting the fix to our 1.10.3 deployment.

**Comment by lblackstone** [comment]
https://community.getcarina.com/t/error-response-from-daemon-on-docker-build/156 is likely the same bug.

**Comment by elephantfries** [comment]
This is blocking me, too.  

However, there is a workaround if the image can be exported to a tarball. The tarball can then be loaded as in image on the target machine.  For this to work, you need a stock OS container with docker and the socket bind mounted to it. While 'docker import' breaks, 'docker build' with a trivial Dockerfile succeeds.  I was able to get me going that way.
FWIW, workaround:
   on your system:
     docker run ... some-image
     docker export > some-image.tar
  then on carina
     docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock ubuntu /bin/bash
  then in the container
     apt-get .... (install docker)
     mkdir build
     scp you@yoursystem:some-image.tar build/
     vi build/Dockerfile
         FROM scratch
         MAINTAINER you@yoursystem
         ADD some-image.tar /
     docker build -t some-image build

You can now start the container as usual

**Comment by lblackstone** [comment]
@vikomall @elephantfries A fix has been pushed for this issue. You will need to create a new cluster to get the updated cluster image. Please let me know if you're still seeing the problem on a new cluster.

**Comment by elephantfries** [comment]
@lblackstone Just created a new cluster and was able to load an image. Looks good.  Thank you so much.

**Comment by everett-toews** [comment]
@elephantfries Thanks for your debugging efforts!
