### ISSUE TITLE
carina get with --wait switch is taking long time

### ISSUE THREAD

**Issue by vikomall** [getcarina/feedback#66]
Repro instructions:
1. Create a cluster and wait for cluster to become active
2. Now try 'carina get <cluster-name> --wait'
This command is taking on average approx 40secs.

**Comment by carolynvs** [comment]
Weird! I am able to reproduce this when I call `get --wait`. When I leave off `--wait` the command returns immediately. I'll dig into this further and see what's up.

**Comment by carolynvs** [comment]
I've confirmed the issue and created a bug report in the carina cli repository to track it. https://github.com/getcarina/carina/issues/105

Thanks for letting us know about the problem!

**Comment by vikomall** [comment]
@carolynvs thanks for creating a bug. Hopefully it will be fixed soon!
