### ISSUE TITLE
Windows setup: Could not read CA certificate

### ISSUE THREAD

**Issue by MECU** [getcarina/feedback#72]
On step 7 of [Getting Started on Carina](https://getcarina.com/docs/getting-started/getting-started-on-carina/) running `docker.exe info` in Windows PowerShell, I get this error message: 

```
Could not read CA certificate "C:\\Users\\me\\.docker\\ca.pem": open C:\Users\me\.docker\ca.pem: The system cannot find the path specified.
```

I had no problems or errors prior to this point. I don't see anywhere before this that the `.docker` directory is created nor any configurations settings to point to where I downloaded and unzipped my container access files.

I manually created `C:\\Users\\me\\.docker` in PowerShell and moved all the unzipped file in there and the error message went away. I'm not sure if this is correct or there's a setting that needs to be made instead to connect. It seems that putting all docker files into this one directory would be problematic.

**Comment by carolynvs** [comment]
@MECU Thanks for the feedback! The instructions for manually downloading and setting up the docker client are a bit clunky... Now that `dvm`, the Docker Version Manager, is more mature, I recommend using that instead. I'll update the page with new instructions soon but in the meantime, [here are the instructions for Windows](https://github.com/getcarina/dvm#installation).

Basically just run this command to install `dvm`, then follow the instructions output in the console to load the dvm command in every PowerShell session.

```powershell
> iex (invoke-webrequest https://download.getcarina.com/dvm/latest/install.ps1)
Downloading dvm.ps1...
Downloading dvm.cmd...
Downloading dvm-helper.exe...

Docker Version Manager (dvm) has been installed to C:\Users\carolynvs\.dvm

PowerShell Users: Run the following command to start using dvm. Then add it to your PowerShell profile to complete the
installation.
        . C:\Users\carolynvs\.dvm\dvm.ps1

> . C:\Users\carolynvs\.dvm\dvm.ps1
```

Then after you have sourced your docker credentials, run `dvm use` to update your current shell session with the appropriate docker client version.

``` powershell
> .\docker.ps1
> dvm use
1.10.3 is not installed. Installing now...
Installing 1.10.3...
Now using Docker 1.10.3
```

**Comment by carolynvs** [comment]
@MECU I apologize, I mis-read your original comment and thought that you were having trouble with the docker client itself.

After downloading the credentials zip file, and then unzipping it, you should see something like this:

`C:\Users\{yourname}\Downloads\{clusterName}`
- docker.ps1
- ca.pem
- ca-key.pem
- key.pem
- cert.pem
- more files related to Linux/Mac

Then in PowerShell, change into that directory and source the `docker.ps1` file:

```powershell
.\docker.ps1
```

This sets some environment variables which the docker client uses to find the certificates:

```powershell
> get-childitem -path env:DOCKER*

Name                           Value
----                           -----
DOCKER_HOST                    tcp://172.99.77.35:2376
DOCKER_TLS_VERIFY              1
DOCKER_CERT_PATH               C:\Users\carolynvs\Downloads\test
DOCKER_VERSION                 1.10.3
```

What do your Docker environment variables look like? If they aren't set, I think the docker client will look for certificates in a default location which may be what you are running into.

**Comment by carolynvs** [comment]
I hope this worked for you! Please reopen if you continue to have trouble.

**Comment by monster910** [comment]
For what its worth, I found that an old docker installation had Windows environment variables pointing to my Users directory.

I uninstalled Docker, removed all environment variables related to Docker and then reinstalled. Worked perfectly.
