### ISSUE TITLE
anti affinity to support multiple AZs

### ISSUE THREAD

**Issue by jsindy** [getcarina/feedback#8]
Swarm node tagging should allow for anti affinity rules to spread mission critical apps across data centers. Ideally not being reliant on a single physical datacenter.

**Comment by rgbkrk** [comment]
In effect, you're requesting that we begin to [label nodes](https://github.com/docker/swarm/blob/49dc6498c150c34379a8f368087efe7011c42be3/docs/scheduler/filter.md#constraint-filter) with their region. That makes sense, though I have to wonder how reliable a multi-DC swarm cluster would be. For the time being, they're only going to be in one region.

**Comment by jsindy** [comment]
in AWS you have AZs does rackspace not have different DCs in the same Region?

**Comment by rgbkrk** [comment]
Carina is only in one region at the moment and in only one affinity zone.

Rackspace does have multiple DCs for some regions and Affinity Zone support via the compute API is in early access availability.

**Comment by simonjj** [comment]
closing this, continuing via issue #5
