### ISSUE TITLE
Login failed: User 'zhufeiyue22@gmail.com' is disabled.

### ISSUE THREAD

**Issue by zhufeiyue33** [getcarina/feedback#85]
I am a Chinese, I registered an account in https://getcarina.com/, use your server to break through China's network to browse the world (build shadowsocks), and no illegal use of it. Why my account is disabled. I yearn for the freedom of the network, but in China. 
    The following is the specific information：Login failed: User 'zhufeiyue22@gmail.com' is disabled.

**Comment by zhufeiyue33** [comment]
help me!

**Comment by iikira** [comment]
Shadowsocks was abused.so do NOT use it any longer!

**Comment by 7sDream** [comment]
Ditto.

email: didislover@gmail.com

What can I do to make my account available?
