### ISSUE TITLE
Cannot create clusters, status immediately changes to error

### ISSUE THREAD

**Issue by tsaarni** [getcarina/feedback#86]
My cluster got into unresponsive state and after rebuild attempt the status was changed to "error".

I deleted the cluster and tried to recreate new ones, both from CLI and from web gui.  All attempts will immediately report "error" status for the newly created cluster.

My user id is tero.saarni@gmail.com

**Comment by carolynvs** [comment]
Sorry about that, we had a hiccup over the weekend. If you delete and try once more, it should work this time.

**Comment by tsaarni** [comment]
Works perfectly again, thanks!
