### ISSUE TITLE
Unable to create new cluster

### ISSUE THREAD

**Issue by jchappell82** [getcarina/feedback#89]
Upon attempting to create a new cluster (after having deleted all existing clusters on my account), they seem to be going directly from `building` state to `error` after anywhere from just a few seconds to a couple of minutes.

The status page doesn't indicate any known issues, so I thought I'd report it here.

**Comment by thomasem** [comment]
Hey @jchappell82!

Thanks for your feedback.

A great place to post about this sort of issue is our [community forum](https://community.getcarina.com). If you're on Freenode IRC, please feel free to drop by `#carina` and ping `thomasem`. I would be happy to dig in further there with you.

I just updated the status page to reflect the problem.

As a heads up, we've been having some capacity issues behind-the-scenes that we're working on addressing in a larger way than we were able to earlier this week.

**Comment by jchappell82** [comment]
Thanks - I actually opened that discussion first https://community.getcarina.com/t/cannot-create-new-cluster/306

Appreciate you looking into it!

**Comment by thomasem** [comment]
@jchappell82 Ohh! My apologies. I did not see that yet. I replied there.
