### ISSUE TITLE
Error when connecting to cluster. Host dead

### ISSUE THREAD

**Issue by dalareo** [getcarina/feedback#92]
I get this error when trying to connect to my cluster:

An error occurred trying to connect: Get https://104.130.22.55:2376/v1.24/info: dial tcp 104.130.22.55:2376: getsockopt: no route to host

It is a legacy cluster with Docker Swarm 1.1.0

**Comment by carolynvs** [comment]
When a cluster goes down, you can try to rebuild it but if that doesn't work the only solution is to create another, redeploy your containers and delete the old one.

Unfortunately, we have hit capacity and creating new clusters has been temporarily disabled. You can subscribe to https://status.getcarina.com/incidents/7fwlbm421737 to receive an update when this restriction has been lifted.
