### ISSUE TITLE
Unable to sign up: "Sorry, we were unable to complete your signup request."

### ISSUE THREAD

**Issue by evanmcd** [getcarina/feedback#94]
Hi,
I've tried multiple email addresses, passwords, and browsers but get the same message every time.

**Comment by carolynvs** [comment]
The Carina beta is at full capacity and we are temporarily not accepting new sign-ups. We will be allowing new users again in the coming weeks, but I don't have an exact date. If you subscribe to our [status updates](https://status.getcarina.com/), you'll receive a notification when you can sign up.
